

spring:
  application:
    name: website

  jmx:
    enabled: false

  messages:
    basename: i18n/messages

  main:
    allow-bean-definition-overriding: true

  task:
    execution:
      thread-name-prefix: website-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: website-scheduling-
      pool:
        size: 2

  thymeleaf:
    mode: HTML

  jooq:
    sql-dialect: postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/website
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari

server:
  servlet:
    session:
      cookie:
        http-only: true
  error:
    whitelabel:
      enabled: false

website:
  url: http://localhost:3000

  cors:
    allowed-origins: ${website.url}
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

  mail:
    from: website@localhost

  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461

error:
  handling:
    http-status-in-json-response: true
    search-super-class-hierarchy: true
    messages:
      java.lang.Throwable: 'Internal Server Error'
      java.sql.SQLException: 'Internal Server Error'
      java.sql.DataAccessException: 'Internal Server Error'
    http-statuses:
      io.jsonwebtoken.ExpiredJwtException: 'UNAUTHORIZED'