spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true

  jackson:
    serialization:
      indent-output: true

  flyway:
    locations: classpath:/db/migration,classpath:/db/test-data
    enabled: true

  mail:
    host: localhost
    port: 2500
    username: username
    password: password
    protocol: smtp

  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard

  thymeleaf:
    cache: false

logging:
  level:
    ROOT: DEBUG
    com.website: DEBUG
    org:
      springframework:
        transaction: DEBUG

website:
  mail:
    base-url: http://127.0.0.1:8080

  security:
    authentication:
      jwt:
        base64-secret: ZTk4YzU0OTRiNDY1YWQ4ZjkwNjBhMWJlN2Y5MGMyYjI4Yjc0ZjhhNzMxYzU2Y2U1OWMwOWRiYTgwYjA4M2NiNGI5NDhiMjQ0NDJhYTVlMTcxODA4NmFjMDg2OTg0NzBiMjUxOTA2YzEyNTE1YTQ5MThiYmVlMzRiNTgxN2U5YmQ=

server:
  port: 8080