version: "3.9"
services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=website
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/docker/volumes/pgdata/_data
volumes:
  pgdata: