/*
 * This file is generated by jOOQ.
 */
package com.website.enbookingbe.data.jooq;


import com.website.enbookingbe.data.jooq.tables.Card;
import com.website.enbookingbe.data.jooq.tables.Quiz;
import com.website.enbookingbe.data.jooq.tables.QuizCard;
import com.website.enbookingbe.data.jooq.tables.Role;
import com.website.enbookingbe.data.jooq.tables.UserCard;
import com.website.enbookingbe.data.jooq.tables.UserRole;
import com.website.enbookingbe.data.jooq.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.card</code>.
     */
    public final Card CARD = Card.CARD;

    /**
     * The table <code>public.quiz</code>.
     */
    public final Quiz QUIZ = Quiz.QUIZ;

    /**
     * The table <code>public.quiz_card</code>.
     */
    public final QuizCard QUIZ_CARD = QuizCard.QUIZ_CARD;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user_card</code>.
     */
    public final UserCard USER_CARD = UserCard.USER_CARD;

    /**
     * The table <code>public.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Card.CARD,
            Quiz.QUIZ,
            QuizCard.QUIZ_CARD,
            Role.ROLE,
            UserCard.USER_CARD,
            UserRole.USER_ROLE,
            Users.USERS
        );
    }
}
