/*
 * This file is generated by jOOQ.
 */
package com.website.enbookingbe.data.jooq;


import com.website.enbookingbe.data.jooq.tables.Card;
import com.website.enbookingbe.data.jooq.tables.Quiz;
import com.website.enbookingbe.data.jooq.tables.QuizCard;
import com.website.enbookingbe.data.jooq.tables.Role;
import com.website.enbookingbe.data.jooq.tables.UserCard;
import com.website.enbookingbe.data.jooq.tables.UserRole;
import com.website.enbookingbe.data.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.card</code>.
     */
    public static final Card CARD = Card.CARD;

    /**
     * The table <code>public.quiz</code>.
     */
    public static final Quiz QUIZ = Quiz.QUIZ;

    /**
     * The table <code>public.quiz_card</code>.
     */
    public static final QuizCard QUIZ_CARD = QuizCard.QUIZ_CARD;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user_card</code>.
     */
    public static final UserCard USER_CARD = UserCard.USER_CARD;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
