/*
 * This file is generated by jOOQ.
 */
package com.website.enbookingbe.data.jooq.tables.records;


import com.website.enbookingbe.data.jooq.tables.Card;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardRecord extends UpdatableRecordImpl<CardRecord> implements Record6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.card.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.card.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.card.question</code>.
     */
    public void setQuestion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.card.question</code>.
     */
    public String getQuestion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.card.answer</code>.
     */
    public void setAnswer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.card.answer</code>.
     */
    public String getAnswer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.card.author_id</code>.
     */
    public void setAuthorId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.card.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.card.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.card.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.card.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.card.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Card.CARD.ID;
    }

    @Override
    public Field<String> field2() {
        return Card.CARD.QUESTION;
    }

    @Override
    public Field<String> field3() {
        return Card.CARD.ANSWER;
    }

    @Override
    public Field<Integer> field4() {
        return Card.CARD.AUTHOR_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Card.CARD.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Card.CARD.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getQuestion();
    }

    @Override
    public String component3() {
        return getAnswer();
    }

    @Override
    public Integer component4() {
        return getAuthorId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getQuestion();
    }

    @Override
    public String value3() {
        return getAnswer();
    }

    @Override
    public Integer value4() {
        return getAuthorId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public CardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CardRecord value2(String value) {
        setQuestion(value);
        return this;
    }

    @Override
    public CardRecord value3(String value) {
        setAnswer(value);
        return this;
    }

    @Override
    public CardRecord value4(Integer value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public CardRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CardRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CardRecord values(Integer value1, String value2, String value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardRecord
     */
    public CardRecord() {
        super(Card.CARD);
    }

    /**
     * Create a detached, initialised CardRecord
     */
    public CardRecord(Integer id, String question, String answer, Integer authorId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Card.CARD);

        setId(id);
        setQuestion(question);
        setAnswer(answer);
        setAuthorId(authorId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
