/*
 * This file is generated by jOOQ.
 */
package com.website.enbookingbe.data.jooq.tables.records;


import com.website.enbookingbe.data.jooq.tables.User;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record15<Integer, String, String, String, String, String, Boolean, String, String, LocalDateTime, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user.activated</code>.
     */
    public void setActivated(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user.activated</code>.
     */
    public Boolean getActivated() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.user.activation_key</code>.
     */
    public void setActivationKey(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user.activation_key</code>.
     */
    public String getActivationKey() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.user.reset_key</code>.
     */
    public void setResetKey(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user.reset_key</code>.
     */
    public String getResetKey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.user.reset_date</code>.
     */
    public void setResetDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user.reset_date</code>.
     */
    public LocalDateTime getResetDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.user.lang_key</code>.
     */
    public void setLangKey(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.user.lang_key</code>.
     */
    public String getLangKey() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.user.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.user.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.user.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.user.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.user.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.user.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.user.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.user.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, String, String, String, String, String, Boolean, String, String, LocalDateTime, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, String, String, String, String, String, Boolean, String, String, LocalDateTime, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return User.USER.IMAGE_URL;
    }

    @Override
    public Field<Boolean> field7() {
        return User.USER.ACTIVATED;
    }

    @Override
    public Field<String> field8() {
        return User.USER.ACTIVATION_KEY;
    }

    @Override
    public Field<String> field9() {
        return User.USER.RESET_KEY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return User.USER.RESET_DATE;
    }

    @Override
    public Field<String> field11() {
        return User.USER.LANG_KEY;
    }

    @Override
    public Field<String> field12() {
        return User.USER.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return User.USER.CREATED_DATE;
    }

    @Override
    public Field<String> field14() {
        return User.USER.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return User.USER.LAST_MODIFIED_DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getImageUrl();
    }

    @Override
    public Boolean component7() {
        return getActivated();
    }

    @Override
    public String component8() {
        return getActivationKey();
    }

    @Override
    public String component9() {
        return getResetKey();
    }

    @Override
    public LocalDateTime component10() {
        return getResetDate();
    }

    @Override
    public String component11() {
        return getLangKey();
    }

    @Override
    public String component12() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedDate();
    }

    @Override
    public String component14() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component15() {
        return getLastModifiedDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getImageUrl();
    }

    @Override
    public Boolean value7() {
        return getActivated();
    }

    @Override
    public String value8() {
        return getActivationKey();
    }

    @Override
    public String value9() {
        return getResetKey();
    }

    @Override
    public LocalDateTime value10() {
        return getResetDate();
    }

    @Override
    public String value11() {
        return getLangKey();
    }

    @Override
    public String value12() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedDate();
    }

    @Override
    public String value14() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value15() {
        return getLastModifiedDate();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public UserRecord value7(Boolean value) {
        setActivated(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setActivationKey(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setResetKey(value);
        return this;
    }

    @Override
    public UserRecord value10(LocalDateTime value) {
        setResetDate(value);
        return this;
    }

    @Override
    public UserRecord value11(String value) {
        setLangKey(value);
        return this;
    }

    @Override
    public UserRecord value12(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public UserRecord value13(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public UserRecord value14(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public UserRecord value15(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, String value8, String value9, LocalDateTime value10, String value11, String value12, LocalDateTime value13, String value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String firstName, String lastName, String email, String password, String imageUrl, Boolean activated, String activationKey, String resetKey, LocalDateTime resetDate, String langKey, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(User.USER);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setPassword(password);
        setImageUrl(imageUrl);
        setActivated(activated);
        setActivationKey(activationKey);
        setResetKey(resetKey);
        setResetDate(resetDate);
        setLangKey(langKey);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }
}
